"""Export Model to Pure Python — Pi Fallback via m2cgen.

Converts the trained sklearn Pipeline inside model_bundle.joblib into
a self-contained pure-Python file (pi/model_pure.py) using m2cgen.

Why this exists
---------------
On a Raspberry Pi Zero / Pi 3 with minimal packages, importing sklearn can
take 5-10 seconds. m2cgen converts the trained tree/linear model into a
single Python function (no sklearn, no numpy required at inference time),
giving near-instant load time.

Limitations
-----------
- Works for: RandomForestClassifier, GradientBoostingClassifier, LinearSVC, LogisticRegression
- Does NOT work for: SVC with RBF kernel (kernel trick not representable as pure math)
- If export fails, falls back gracefully (Person C uses the .joblib directly)

Usage
-----
    python scripts/export_model.py
    python scripts/export_model.py --bundle models/model_bundle.joblib --out pi/model_pure.py

Install m2cgen
--------------
    pip install m2cgen
"""
import os
import sys
import argparse
import textwrap

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


HEADER_TEMPLATE = textwrap.dedent("""\
    # AUTO-GENERATED by scripts/export_model.py — DO NOT EDIT MANUALLY
    # Generated from: {bundle_path}
    # Model:          {model_name}
    # Trained at:     {trained_at}
    # Classes:        {classes}
    # Features:       {n_features}
    #
    # Usage:
    #   import model_pure
    #   score_vector = model_pure.score(feature_list)  # returns list of class scores
    #   pred_class_index = score_vector.index(max(score_vector))
    #
    # CLASSES list (index → label):
{class_lines}

    FEATURE_NAMES = {feature_names!r}
    CLASSES = {classes!r}

""")


def export(bundle_path="models/model_bundle.joblib", out_path="pi/model_pure.py"):
    """Convert sklearn model to pure Python via m2cgen.

    Args:
        bundle_path: Path to model_bundle.joblib.
        out_path:    Destination path for the generated Python file.

    Returns:
        bool: True if export succeeded, False if m2cgen unavailable or unsupported.
    """
    # 1. Load bundle
    from src.bundle import load_bundle
    bundle = load_bundle(bundle_path)
    pipeline  = bundle["pipeline"]
    classes   = bundle["classes"]
    feat_names = bundle["feature_names"]
    model_name = bundle.get("model_name", "unknown")
    trained_at = bundle.get("trained_at", "unknown")

    # 2. Import m2cgen
    try:
        import m2cgen as m2c
    except ImportError:
        print(
            "[export] m2cgen is not installed.\n"
            "         Run: pip install m2cgen\n"
            "         Skipping export — Person C will use .joblib directly."
        )
        return False

    # 3. Extract the actual classifier step from the pipeline
    step = (
        pipeline.named_steps.get("rf")
        or pipeline.named_steps.get("gb")
        or pipeline.named_steps.get("svm")
        or pipeline.named_steps.get("lr")
    )

    if step is None:
        print("[export] Could not locate classifier step in pipeline. Skipping.")
        return False

    # 4. Attempt m2cgen export
    try:
        code = m2c.export_to_python(step)
    except Exception as exc:
        print(
            f"[export] m2cgen export failed: {exc}\n"
            "         This model type (e.g. SVM-RBF) cannot be converted to pure Python.\n"
            "         Person C will use .joblib directly — this is fine."
        )
        return False

    # 5. Build class comment lines for header
    class_lines = "\n".join(
        f"#   {i}: {cls}" for i, cls in enumerate(classes)
    )
    class_lines_indented = "\n".join(
        f"    {line}" for line in class_lines.split("\n")
    )

    header = HEADER_TEMPLATE.format(
        bundle_path=os.path.abspath(bundle_path),
        model_name=model_name,
        trained_at=trained_at,
        classes=classes,
        n_features=len(feat_names),
        class_lines=class_lines_indented,
        feature_names=feat_names,
    )

    # 6. Write output file
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(code)
        f.write("\n\n# End of auto-generated file\n")

    size_kb = os.path.getsize(out_path) / 1024
    print(f"[export] ✓ Pure-Python model exported → {os.path.abspath(out_path)}")
    print(f"         File size: {size_kb:.1f} KB")
    print(f"         Classes:   {classes}")
    print( "         Note: preprocessing (imputer/scaler) NOT included.")
    print( "               Person C must apply the same preprocessing manually,")
    print( "               or just use the .joblib bundle directly.")
    return True


# ---------------------------------------------------------------------------
# Verification: quick sanity check on exported model
# ---------------------------------------------------------------------------

def verify_export(out_path="pi/model_pure.py", n_features=68):
    """Run a quick sanity check on the exported pure-Python file.

    Args:
        out_path:   Path to the generated model_pure.py.
        n_features: Expected number of input features.

    Returns:
        bool: True if verification passed.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location("model_pure", out_path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    dummy_input = [0.0] * n_features
    scores = mod.score(dummy_input)

    print(f"[export] Verification: score({n_features} zeros) → {scores}")
    print(f"[export] ✓ Exported model runs correctly.")
    return True


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export sklearn model to pure Python via m2cgen"
    )
    parser.add_argument(
        "--bundle", type=str, default="models/model_bundle.joblib",
        help="Path to model_bundle.joblib"
    )
    parser.add_argument(
        "--out", type=str, default="pi/model_pure.py",
        help="Output path for generated pi/model_pure.py"
    )
    parser.add_argument(
        "--verify", action="store_true",
        help="Run a quick verification check on the exported file"
    )
    args = parser.parse_args()

    success = export(bundle_path=args.bundle, out_path=args.out)
    if success and args.verify:
        from src.features import FEATURE_NAMES
        verify_export(out_path=args.out, n_features=len(FEATURE_NAMES))
